/* Generated By:JavaCC: Do not edit this line. SentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int I = 4;
  /** RegularExpression Id. */
  int YOU = 5;
  /** RegularExpression Id. */
  int ME = 6;
  /** RegularExpression Id. */
  int LOVE = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"I\"",
    "\"YOU\"",
    "\"ME\"",
    "\"LOVE\"",
  };

}
