/* Generated By:JJTree: Do not edit this line. ASTMulti.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=javacc.expr.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.expr.parser;

public
class ASTMulti extends SimpleNode {
  public ASTMulti(int id) {
    super(id);
  }

  public ASTMulti(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4d590e66430a6e73bbdfcf196c7cf647 (do not edit this line) */
