/* Generated By:JavaCC: Do not edit this line. ExprParserVisitor.java Version 5.0 */
package javacc.expr.parser;

public interface ExprParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=464515ce4672cf1e8e538b402a8826f0 (do not edit this line) */
