/* Generated By:JJTree: Do not edit this line. ASTWord.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=location.query.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package location.query.parser;

public
class ASTWord extends SimpleNode {
  public ASTWord(int id) {
    super(id);
  }

  public ASTWord(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9361fb1cda3e3d74657d9573879bf89f (do not edit this line) */
