/* Generated By:JJTree&JavaCC: Do not edit this line. QueryParserConstants.java */
package location.query.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 4;
  /** RegularExpression Id. */
  int LP = 5;
  /** RegularExpression Id. */
  int RP = 6;
  /** RegularExpression Id. */
  int QUOTE = 7;
  /** RegularExpression Id. */
  int OP_AND = 8;
  /** RegularExpression Id. */
  int OP_OR = 9;
  /** RegularExpression Id. */
  int OP_NOT = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<WORD>",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "<OP_AND>",
    "<OP_OR>",
    "<OP_NOT>",
  };

}
