/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 5.0 */
package location.query.parser;

public interface QueryParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTAND = 2;
  public int JJTOR = 3;
  public int JJTNOT = 4;
  public int JJTLP = 5;
  public int JJTRP = 6;
  public int JJTWORD = 7;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "And",
    "Or",
    "Not",
    "Lp",
    "Rp",
    "Word",
  };
}
/* JavaCC - OriginalChecksum=597ce2e1a6837349ad97fe13cf437cf0 (do not edit this line) */
