/* Generated By:JavaCC: Do not edit this line. QueryParserVisitor.java Version 5.0 */
package location.query.parser;

public interface QueryParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTLp node, Object data);
  public Object visit(ASTRp node, Object data);
  public Object visit(ASTWord node, Object data);
}
/* JavaCC - OriginalChecksum=d3bd60c56f7a1e64f489dde9a9fc6a0b (do not edit this line) */
