/* Generated By:JJTree: Do not edit this line. ASTQuote.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=location.qbss.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package location.qbss.parser;

public
class ASTQuote extends SimpleNode {
  public ASTQuote(int id) {
    super(id);
  }

  public ASTQuote(QbSSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QbSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6821f243946cc7112054898732a1b024 (do not edit this line) */
