/* Generated By:JJTree: Do not edit this line. ASTWord.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=location.qbss.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package location.qbss.parser;

public
class ASTWord extends SimpleNode {
  public ASTWord(int id) {
    super(id);
  }

  public ASTWord(QbSSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QbSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eb4afbd767acda3c4ba8f05171b29651 (do not edit this line) */
