/* Generated By:JJTree&JavaCC: Do not edit this line. QbSSParserConstants.java */
package location.qbss.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QbSSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OP_AND = 5;
  /** RegularExpression Id. */
  int OP_OR = 6;
  /** RegularExpression Id. */
  int OP_NOT = 7;
  /** RegularExpression Id. */
  int WORD = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "<WORD>",
  };

}
