/* Generated By:JavaCC: Do not edit this line. QbSSParserVisitor.java Version 5.0 */
package location.qbss.parser;

public interface QbSSParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTWord node, Object data);
}
/* JavaCC - OriginalChecksum=b53cd3bf525e1a3ad42336b08192ba26 (do not edit this line) */
