/* Generated By:JavaCC: Do not edit this line. QbSSParserTreeConstants.java Version 5.0 */
package location.qbss.parser;

public interface QbSSParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTAND = 2;
  public int JJTOR = 3;
  public int JJTNOT = 4;
  public int JJTQUOTE = 5;
  public int JJTWORD = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "And",
    "Or",
    "Not",
    "Quote",
    "Word",
  };
}
/* JavaCC - OriginalChecksum=63350cb288173b126c9a1689647d5b93 (do not edit this line) */
