/* Generated By:JavaCC: Do not edit this line. QbSSParserVisitor.java Version 5.0 */
package location.qbss.parser;

public interface QbSSParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTQuote node, Object data);
  public Object visit(ASTWord node, Object data);
}
/* JavaCC - OriginalChecksum=5672c12e17247ae98b4209979ce21ec6 (do not edit this line) */
