/* Generated By:JJTree&JavaCC: Do not edit this line. QbSSParserConstants.java */
package location.qbss.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QbSSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OP_AND = 6;
  /** RegularExpression Id. */
  int OP_OR = 7;
  /** RegularExpression Id. */
  int OP_NOT = 8;
  /** RegularExpression Id. */
  int WORD = 9;
  /** RegularExpression Id. */
  int LP = 10;
  /** RegularExpression Id. */
  int RP = 11;
  /** RegularExpression Id. */
  int QUOTE = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\u3000\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "<WORD>",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
  };

}
