/* Generated By:JavaCC: Do not edit this line. QbSSParserTreeConstants.java Version 5.0 */
package location.qbss.parser;

public interface QbSSParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTAND = 2;
  public int JJTOR = 3;
  public int JJTNOT = 4;
  public int JJTWORD = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "And",
    "Or",
    "Not",
    "Word",
  };
}
/* JavaCC - OriginalChecksum=5de5d4ced6b3135bb3c4f8317121e7bc (do not edit this line) */
