/* Generated By:JJTree: Do not edit this line. ASTDivision.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=javacc.expr.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc.expr.parser;

public
class ASTDivision extends SimpleNode {
  public ASTDivision(int id) {
    super(id);
  }

  public ASTDivision(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=234fe0e8a6948300fb00f860dea8add7 (do not edit this line) */
