/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 5.0 */
package javacc.expr.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMULTI = 4;
  public int JJTDIVISION = 5;
  public int JJTINTEGER = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Sub",
    "Multi",
    "Division",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=dd6a87dbf3684e5abb0e96373793ecea (do not edit this line) */
